---
version: '2'

services:

  grafana:
    image: grafana/grafana
    restart: always
    entrypoint:
      - bash
      - -c
      - grafana-cli plugins install grafana-piechart-panel && /run.sh
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana-data:/var/lib/grafana
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    extra_hosts:
      - "mini-monitor:192.168.86.209"
    command: |-
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
      --storage.tsdb.retention.time=90d
      --web.console.libraries=/usr/share/prometheus/console_libraries
      --web.console.templates=/usr/share/prometheus/consoles
      --web.enable-admin-api
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
      - ./prometheus/rules:/prometheus_rules
    mem_limit: 2G
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  alertmanager:
    image: prom/alertmanager
    restart: always
    ports:
      - "9093:9093"
    command: --config.file=/etc/prometheus/alertmanager.yml
    volumes:
      - ./prometheus/alertmanager.yml:/etc/prometheus/alertmanager.yml:ro
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  loki:
    image: grafana/loki:master
    restart: always
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yml
    volumes:
      - ./loki/loki.yml:/etc/loki/loki.yml
      - ./loki_data_11-2021:/loki_data
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: 'http://localhost:3100/api/prom/push'

  process_exporter:
    image: ncabatoff/process-exporter
    restart: always
    command: -config.path /config/process-exporter.yml -procfs /host/proc
    privileged: true
    volumes:
      - ./process_exporter:/config
      - /proc:/host/proc
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  external_exporter:
    build: external_exporter
    restart: always
    env_file: .env
    command: $VALIDATOR_ADDRESS 60 $VALIDATOR_URL
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  # spectroscope:
  #   build: spectroscope
  #   env_file: .env
  #   #command: spectroscope run -c /config/config.toml
  #   command: --config /config/config.toml
  #   restart: always
  #   volumes:
  #     - ./spectroscope/config:/config
  #   logging:
  #     driver: loki
  #     options:
  #       loki-url: 'http://localhost:3100/api/prom/push'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.38.8
    restart: always
    privileged: true
    ports:
      - "$CADVISOR_PORT:8080"
    devices:
      - "/dev/kmsg:/dev/kmsg"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  json_exporter:
    #image: quay.io/prometheuscommunity/json-exporter
    image: doubtingben/json_exporter@sha256:edea98337045e7835c91b98e2d40875ba89a3a6c165be391cf91fb5ea7edde15
    restart: always
    ports:
      - "7979:7979"
    command: --config.file=/json_exporter/config.yaml
    volumes:
      - ./json_exporter/:/json_exporter/:ro
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'