---
version: '2'

services:

  grafana:
    image: grafana/grafana
    entrypoint:
      - bash
      - -c
      - grafana-cli plugins install grafana-piechart-panel && /run.sh
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana-data:/var/lib/grafana
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    extra_hosts:
      - "mini-monitor:192.168.86.209"
    command: |-
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
      --web.console.libraries=/usr/share/prometheus/console_libraries
      --web.console.templates=/usr/share/prometheus/consoles
      --web.enable-admin-api
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
      - ./prometheus/rules:/prometheus_rules
    mem_limit: 2G
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    command: --config.file=/etc/prometheus/alertmanager.yml
    volumes:
      - ./prometheus/alertmanager.yml:/etc/prometheus/alertmanager.yml:ro
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  loki:
    image: grafana/loki:master
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yml
    volumes:
      - ./loki/loki.yml:/etc/loki/loki.yml
      - ./loki_data:/loki_data
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: 'http://localhost:3100/api/prom/push'

  process_exporter:
    image: ncabatoff/process-exporter
    command: -config.path /config/process-exporter.yml -procfs /host/proc
    privileged: true
    volumes:
      - ./process_exporter:/config
      - /proc:/host/proc
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'        

  external_exporter:
    build: external_exporter
    env_file: .env
    command: $VALIDATOR_ADDRESS 60 $VALIDATOR_URL
    restart: always
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'        

