global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10m
  repeat_interval: 1h
  receiver: 'default'
receivers:
  - name: 'default'
    pushover_configs:
      - send_resolved: true
        user_key: <I REMOVED THE APP>
        token: <I REMOVED THE APP>
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
