global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10m
  repeat_interval: 1h
  receiver: 'default'
receivers:
  - name: 'default'
    pushover_configs:
      - send_resolved: true
        user_key: ux637dzjj8br8k6peqej2sa8czptek
        token: aevh4m4f8y91m1ud2zni4h85inzs4u
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
