# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  
# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - 'alertmanager:9093'
  
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - '/prometheus_rules/*yml'
  # - "first_rules.yml"
  # - "second_rules.yml"
  
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
  - job_name: node_exporter
    static_configs:
      - targets: 
          - mini-monitor:9100
          - super-mini:9100
          - linux-1050:9100
  - job_name: process_exporter
    static_configs:
      - targets: 
          - process_exporter:9256
  - job_name: external_exporter
    static_configs:
      - targets: 
          - external_exporter:9010
  - job_name: geth_metrics_expars
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: 
          - linux-1050:9091
          - super-mini:9091
  - job_name: geth_exporter
    static_configs:
      - targets: 
          - linux-1050:9092
          - super-mini:9092
  - job_name: lighthouse_beacon_node
    static_configs:
      - targets: 
          - linux-1050:5054
          - super-mini:5054    
  - job_name: lighthouse_validator_client
    static_configs:
      - targets: 
          - linux-1050:5064
          - super-mini:5064
  
